### ISSUE TITLE
手机上配置xtcp的P2P连接方式，连接失败，在PC上面运行是没问题的

### ISSUE THREAD

**Issue by TNT-DG** [AceDroidX/frp-Android#12]
配置参数：
```
[common]
server_addr = xx.xx.xx.xx
server_port = 7000

[Mstsc_visitor]
type = xtcp
role = visitor
server_name = Mstsc
sk = xxxxx
bind_addr = 127.0.0.1
bind_port = 8001
```
报错日志：
![微信图片_20240509172533](https://github.com/AceDroidX/frp-Android/assets/29853150/9ea6758e-2a1a-4c18-8ea0-9320baf0747b)

PC端用的frp是0.5x版本的

**Comment by AceDroidX** [comment]
1.
`2024-05-09 09:09:10.256 [W] [visitor/ visitor_manager.go:118] [2b52090462ce8754] start error: listen tcp 127.0.0.1:8001: bind: address already in use`
Android的8001端口已被占用 请检查是否有其他应用占用了此端口
也有可能是软件bug导致重复多开frpc实例 在系统设置里对软件强行停止后再次尝试
2.
`2024-05-09 09:09:23.442 [W] [visitor/ xtcp.go:280] [2b52090462ce8754] [Mstsc_visitor]
nathole prepare error: discover error: lookup stun.easyvoip.com on [::1]:53: read udp
[::1]:41120->[::1]:53: read: connection refused`
DNS服务器无法连接
尝试在配置里添加dnsServer
<https://gofrp.org/zh-cn/docs/reference/client-configures/#clientcommonconfig>
3.
ini格式已弃用 建议按官网教程使用toml格式
<https://gofrp.org/zh-cn/docs/examples/xtcp/>

**Comment by TNT-DG** [comment]
谢谢回答。我强制关闭软件确认端口没有被占用后，然后在配置中也添加了dnsServer为114.114.114.114，但是还是失败。
另外这个配置文件的格式可以自己设置吗？
![微信图片_20240509183019](https://github.com/AceDroidX/frp-Android/assets/29853150/fdac1a4e-154d-45c0-89ec-cc96b0ae27c0)

**Comment by AceDroidX** [comment]
看来确实有重复多开frpc实例的可能性 这我之后再修吧 先强行停止应付一下（

我那README里的写法是ini的 忘更新了
dnsServer的写法是toml的
先照官网那例子改一下 然后再把dnsServer加进去
例如：
```toml
serverAddr = "<服务器地址>"
serverPort = 7000
dnsServer = "114.114.114.114"

[log]
level = "debug"
disablePrintColor = true

[[visitors]]
name = "Mstsc_visitor"
type = "xtcp"
# 要访问的 P2P 代理的名称
serverName = "Mstsc"
secretKey = "xxxxxxxx"
# 绑定本地端口以访问 SSH 服务
bindAddr = "127.0.0.1"
bindPort = 8001
# 如果需要自动保持隧道打开，将其设置为 true
# keepTunnelOpen = false
```
